[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
#    "-Clink-args=-Tsrc/linker_nosbi.ld", "-Cforce-frame-pointers=yes"
]